### ISSUE TITLE
Not working on Jenkins version 2.440.1

### ISSUE THREAD

**Issue by caohuileon** [jenkinsci/locale-plugin#190]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

This plugin not working on Jenkins version 2.440.1 or higher than 2.426.2

### Reproduction steps

Upgrade jenkins version to 2.440.1 will see plugin report error

### Expected Results

plugin should work

### Actual Results

not able to get plugin work and it will lead jenkins upgrade failed

**Comment by jonesbusy** [comment]
I please add more information like logs, list of plugin etc (https://www.jenkins.io/participate/report-issue/#what-information-to-provide-for-environment-and-description)

On my side I confirm the plugin is working latest LTS version

![works](https://github.com/jenkinsci/locale-plugin/assets/825750/762eb4f2-bc35-4a9b-afcc-3fcdeb2b1443)
