### ISSUE TITLE
Add help for the locale field

### ISSUE THREAD

**Issue by mawinter69** [jenkinsci/locale-plugin#211]
### What feature do you want to see added?

It is totally unclear what you have to enter in the locale field. Only from the plugin page I could deduct that `en` is valid. 
But what about e.g. `en_US` does it work?
So it would be good if the locale field gets some help with samples of allowed values. Ideally the locale field is a dropdown where you select a language but specifying the locale can be quite tricky afaik.

**Comment by ganesh-sadanala** [comment]
@mawinter69 can you assign this to me?

**Comment by jonesbusy** [comment]
Fixed by #215
