### ISSUE TITLE
Documentation indicates wrong place for locale section

### ISSUE THREAD

**Issue by Coder-Pilgrim** [jenkinsci/locale-plugin#213]
### Describe your use-case which is not covered by existing documentation.

In the documentation it is indicated that Locale section is under Manage Jenkins > Configure System however in my case it was under Manage Jenkins >Appearance. I am using version 495.v4606fdb_134ef.

**Comment by GeneralMidiRotkiv** [comment]
This problem took a solid 20 minutes, a couple of restarts & re-installs and a lot of mental sanity from me...

**Comment by CCodeInspect** [comment]
And me too,Jenkins 2.452.2,I can not find the locale section.

**Comment by jonesbusy** [comment]
Release notes of https://github.com/jenkinsci/locale-plugin/releases/tag/495.v4606fdb_134ef

Documentation was forgotten. Feel free to open a PR to update the documentation.

Thanks

**Comment by Coder-Pilgrim** [comment]
Documentation updated closing this issue.

**Comment by jonesbusy** [comment]
Thanks!
