### ISSUE TITLE
Swedish translation is not shown

### ISSUE THREAD

**Issue by nafmo** [jenkinsci/locale-plugin#264]
### Jenkins and plugins versions report

I am having problems getting the Jenkins UI to show up in anything but English. My browser correctly outputs an Accept-Language string:

    Accept-Language: sv,nb;q=0.9,en-US;q=0.8,en;q=0.7

but the user interface still displays in English.

If I request the same document with my phone browser, the UI shows in Swedish, so I know it is capable. The mobile version sends

    Accept-Language: sv-SE,sv;q=0.9,nb-NO;q=0.8,nb;q=0.7,en-GB;q=0.6,en;q=0.5,en-US;q=0.4

According to the [this thread](https://community.jenkins.io/t/user-interface-displays-in-english/22643), the problem is that the language list in this plugin is too narrow, it only lists (sv-SE) "Swedish as spoken in Sweden", not "Swedish" (sv), and the latter is what my desktop browser asks for. Please change "sv_SE" in the plugin language list to "sv" to make the Swedish translation available to all.

The other locale using Swedish is "sv-FI" (Swedish as spoken in Finland), and if it anyone at any point in the future want to make a different translation of something for this, they can be split, but, being involved in Swedish localization of software myself, I don't see that happening.

### What Operating System are you using (both controller, and any agents involved in the problem)?

Server: Jenkins 2.462.3 installed from .deb package, running on an Ubuntu 24.04 LTS server.

Browser: Using Vivaldi (7.0.3495.6) on Debian desktop (displays English) and Vivaldi for Android (6.9.3451.114).

### Reproduction steps

Desktop: Browser is configured to display Swedish (sv) as the first choice.

Mobile: Browser picks up on OS settings (which has Swedish as the first choice).

### Expected Results

Both browsers should display the Swedish translation.

### Actual Results

Only when displayed through the phone browser, the UI shows in Swedish

**Comment by jonesbusy** [comment]
Released on https://github.com/jenkinsci/locale-plugin/releases/tag/546.v1609030511ca_
